### PR TITLE
Adding automatic installation script

### PR DESCRIPTION
**Pull request by rudisimo**
I've added a Rakefile for easier installation into the user stylesheet directory. The script supports Chrome and Chrome Canary, plus it will install the stylesheet on all available profiles. To use it, run `rake` from the source directory.

### CODE REVIEW

**Comment by s10wen** [comment]
A_W_E_S_O_M_E

Would it be possible to do the reverse as well?

**Comment by rudisimo** [comment]
@simonowendesign Sure, the only thing to watch out for is a user with multiple profiles. I could give them the choice to pull the Custom.css file from a specific profile, like so:

```
Chrome Profiles
  [1] Default
  [2] Profile 1
  [3] Profile 2

Please choose your profile: [1]
```

**Comment by s10wen** [comment]
Sgtm :squirrel:

**Comment by mauricecruz** [comment]
Hey @rudisimo, Thanks for building this!

I tested this on Windows.  There's a few issues:
1.  Not sure why but on Windows, Chrome Canary directory is called "Chrome SxS".  Simple fix though.
2.  The backup feature is not working.

Also, it would be nice to implement the choice interface you suggested.  I don't think it's fair to assume every profile would want to use the same theme.

**Comment by s10wen** [comment]
Yeah, sorry that got fixed after I'd done the PR - https://github.com/simonowendesign/SO-Dark-Monokai-v3/commit/febebd69afa40cb577d2d558c9c37f8c9bc2d151

**Pull request merged**
