### PR TITLE
some fixes on toolbar, settings and sub bar on network

### PR DESCRIPTION
**Pull request by RaphaelDDL**
Regarding issue #23 and other stuff.

### CODE REVIEW

**Comment by s10wen** [comment]
Thanks big improvement :sunglasses:, please watch your formatting though, I'll merge this then tidy up in another commit :squirrel:

Tbh I could do with cleaning the whole thing up at some point.

**Comment by s10wen** [comment]
@RaphaelDDL here's what I meant re formatting: https://github.com/simonowendesign/SO-Dark-Monokai-v3/commit/190f42ca276c99c3a74fe1c556549090a5deb0e9

**Comment by RaphaelDDL** [comment]
@simonowendesign Ah ok. Sorry, should've looked how your formatting was and followed. My default formatting is without spaces and selects without lines (I hate spaces lol).

By the way, I was thinking in getting the custom.css and split it into smaller sass files (tabs, etc), and just import them all later, what you think?

**Comment by s10wen** [comment]
Yeah, I've been thinking about this for a while (and actually started it) I need to plan in some time and get it all sorted. Thanks for the offer, will bear it in mind if/when I get around to it.

**Pull request merged**
