### PR TITLE
#-webkit-web-ISpector to #-webkit-web-INspector

### PR DESCRIPTION
**Pull request by james2doyle**

### CODE REVIEW

**Comment by s10wen** [comment]
:bowtie: Nice spot, ta.

**Comment by james2doyle** [comment]
I went to add a new style and sublime came up with the ispector auto-complete and I said "hold on!". So all the credit goes to Sublime :smile:

**Comment by s10wen** [comment]
Awesome, keep me posted, interested to see what changes you make. Going to spend some time on this soon, as I know there's still a few bits to improve.

**Comment by james2doyle** [comment]
Yeah of course. I find it sometimes really confusing which classes are overriding which. It's nothing like a regular web page.

**Comment by s10wen** [comment]
Yup, also the original one I forked it from is littered with !important tags, not sure they're all needed.

**Comment by james2doyle** [comment]
I think the custom.css file loads before the devTools.css file and thats
why all the !important tags are there.

On Thu, Jan 10, 2013 at 10:59 AM, Simon Owen Design <
notifications@github.com> wrote:

> Yup, also the original one I forked it from is littered with !important
> tags, not sure they're all needed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/simonowendesign/SO-Dark-Monokai-v3/pull/1#issuecomment-12103586.

## 

_James Doyle              (._. )_
Front-End Web Developer
http://ohdoylerules.com/

**Pull request merged**
