### PR TITLE
Fix invisible underscores in console by enlarging the font one pixel.

### LINKED ISSUE #11: Invisible underscores, call stack
Hey, I haven't seen any search results on this so I'm wondering if it's just me.. I can't see underscores or odd-numbered functions in the call stack.

underscore

callstack

I selected that second-to-last function so you could see what I mean.. Is there anything I can do about this? Makes coding kinda like a hide-and-seek.  :)

### PR DESCRIPTION
**Pull request by darvelo**
Fixes #11

### CODE REVIEW

**Comment by s10wen** [comment]
Please can you do me a favour and put up a screenshot.

**Comment by darvelo** [comment]
Sure. This is what an example of the applied style looks like with the HTML:
new
You can see that it says the devTools.css rule is applied, even though the Custom.css stylesheet should override it.

not-applied

If I check by changing Custom.css directly:
applied
unapplied

**Comment by s10wen** [comment]
:heartpulse: Nice job man :heartpulse:

**Comment by darvelo** [comment]
Thanks! :D  :heart:

**Pull request merged**
