### PR TITLE
slight tweaks and modernizations 

### PR DESCRIPTION
**Pull request by smergler**
- adding sidebar-pane to fit with chrome 26's layout 
- commenting out certain .selected styles so we keep 
  an input text cursor
- few stylistic color changes for higher contrast to match with 
  Monokai's color theme 
- showing certain triangles white because they were black before 
  (black on black is not good)

committed & developed with help from DefiantBidet

### CODE REVIEW

**Comment by s10wen** [comment]
Awesome dude! Had noticed the black on black triangles, was on my to do list. Will check over. If you have time, would be cool if you could attach some screenshots so I know where to look.

**Comment by s10wen** [comment]
Careful with those arrows, looks like some are appearing where they shouldn't be:
Screen Shot 2013-03-27 at 21 23 02

**Comment by DefiantBidet** [comment]
yeah we're seeing that.... looking into it now. Thanks for the awesome response time, however!

**Comment by smergler** [comment]
Fixed that arrow problem.  
Screen Shot 2013-03-27 at 5 44 18 PM

**Comment by smergler** [comment]
Screenshot showing that the cursor works 

Screen Shot 2013-03-27 at 5 47 56 PM

**Comment by DefiantBidet** [comment]
attaching some more screenies of things that changed most, elements panel and sources pane.
elements-panel
sources-panel

sources panel doesn't have black on black copy in right panels anymore.
arrows, and high contrast copy in elements side panel as well.

**Comment by s10wen** [comment]
Cool, just looking over.

**Comment by s10wen** [comment]
Just wondering why you've deleted some code, like the 'Sources' section? Getting:

Screen Shot 2013-03-27 at 22 07 10

Should look like this:
Screen Shot 2013-03-27 at 22 18 02

**Comment by DefiantBidet** [comment]
interesting. I've never seen that panel styled properly. Hence why we removed it, it wasn't changing anything for us. Now we know (thanks) we can take a look. Chances are its like the sidebar, a recent update in Chrome changed the classname.

**Comment by s10wen** [comment]
Ah, that'll explain it then. Just looking over it and it's getting a bit confusing as normally when I edit the css, I see changes straight away, but just discovered this isn't the case at the minute and having to close the tab down and open a new tab to see changes.

**Comment by s10wen** [comment]
Going to look at cherry picking the code and adding as separate commits so it's easier to see what bits of code are related to what. Hopefully help going forward if the class names change.

**Comment by s10wen** [comment]
Can you do me a favour please, I've deleted the code that was causing the input cursor to vanish, so that's one thing sorted :smile:. Are you ok to take the latest version now and add in your changes one at a time? No worries if not I'll look at it later in the week. Thanks for your help on this, looking good! :thumbsup:

**Comment by s10wen** [comment]
This is where I was up to with the sources bit:
Screen-Shot-2013-03-22-at-12 29

**Comment by s10wen** [comment]
Have added: 'input text cursor' and 'triangles'.

If you could implement the other bits you'd done as I have (if you check my previous commits), small commits with images of 'From and To', that would be cool, then I can get a PR from you, also please watch the tabbing :see_no_evil:.

Ta.

**Pull request closed without merging**
